namespace Stats
{
    public enum CharacterStat
    {
        Health,
        MagicArmor,
        PhysicArmor,
        ExperienceReward,
        ExperienceToLevelUp,
        CarryWeight,
        Speed,
        Initiative,
        StrengthDamage,
        FinesseDamage,
        IntelligenceDamage,
        CriticalChance,
        FireResistance,
        WaterResistance,
        EarthResistance,
        AirResistance,
        PoisonResistance,
        Accuracy,
        Dodging,
        Strength,
        Finesse,
        Intelligence,
        Constitution,
        Wits
    }
}